project:
  type: book

book:
  title: "Introduction to Data Science"
  subtitle: "STAT 3255/5255 @ UConn, Fall 2024"
  author:
    - name: "Jun Yan and Students in Fall 2024"
  date: today

  sidebar:
    logo: images/ids-s24.png
  
  chapters:
    - index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt

execute:
  freeze: auto
